config/routes.rb
Artie::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :customers
  resources :incoming_rfqs
  resources :parts
  resources :drawings

  root to: 'static_pages#home'
  match '/createcustomer',  to: 'customers#new'
  match '/createuser',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/incoming_rfq.rb
# == Schema Information
#
# Table name: incoming_rfqs
#
#  id         :integer          not null, primary key
#  from       :string(255)
#  subject    :text
#  text_body  :text
#  html_body  :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  originator :string(255)
#

class IncomingRfq < ActiveRecord::Base

  attr_accessible :from, :html_body, :originator, :subject, :text_body
  has_many :incoming_rfq_attachments, dependent: :destroy
  has_many :incoming_rfq_items, dependent: :destroy

  before_save do |incoming_rfq|
    incoming_rfq.from = from.downcase
    incoming_rfq.originator = originator.downcase
  end

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :from, presence: true, format: { with: VALID_EMAIL_REGEX }
  validates :originator, presence: true, format: { with: VALID_EMAIL_REGEX }

  default_scope order: 'incoming_rfqs.created_at DESC'

end

app/controllers/incoming_rfqs_controller.rb
class IncomingRfqsController < ApplicationController

  before_filter :internal_user

  # NOT implemented
  def edit
    @incoming_rfq = IncomingRfq.find(params[:id])
  end

  def update
    @incoming_rfq = IncomingRfq.find(params[:id])
    if @incoming_rfq.update_attributes(params[:incoming_rfq])
      flash[:success] = "RFQ changes saved"
      redirect_to @incoming_rfq
    else
      render 'edit'
    end
  end

  def show
    @incoming_rfq = IncomingRfq.find(params[:id])
    @incoming_rfq_items = @incoming_rfq.incoming_rfq_items.all
  end

  # NOT implemented
  def new
    @incoming_rfq = IncomingRfq.new
  end

  def create
    @incoming_rfq = IncomingRfq.new(params[:incoming_rfq])
    if @incoming_rfq.save
      flash[:success] = "New RFQ created"
      redirect_to @incoming_rfq
    else
      render 'new'
    end
  end

  def index
    @incoming_rfqs = IncomingRfq.paginate(page: params[:page])
  end

  def destroy
    IncomingRfq.find(params[:id]).destroy
    flash[:success] = "RFQ deleted"
    redirect_to incoming_rfqs_url
  end

end

app/views/incoming_rfqs/_incoming_rfq.html.erb
<li>
  QN<%= incoming_rfq.id %>: <%= link_to incoming_rfq.subject, incoming_rfq %>
  | Originator: <%= incoming_rfq.originator %>
  | Forwarder: <%= incoming_rfq.from %>
  | <%= pluralize(incoming_rfq.incoming_rfq_items.count, "item") %>
  <% if current_user.admin? %>
      | <%= link_to "delete", incoming_rfq, method: :delete,
                    data: { confirm: "Are you sure you want to delete this?" } %>
  <% end %>
</li>

app/views/incoming_rfqs/index.html.erb
<% provide(:title, 'List All Incoming RFQs') %>
<h1>Incoming RFQs</h1>

<%= will_paginate %>

<ul class="incoming_rfqs">
  <%= render @incoming_rfqs %>
</ul>

<%= will_paginate %>

app/views/incoming_rfqs/show.html.erb
<% provide(:title, @incoming_rfq.subject) %>
<h1>
  QN<%= @incoming_rfq.id %>: <%= @incoming_rfq.subject %>
</h1>
<div class="row">
  <aside class="span4">
    <section>
      Originator: <%= @incoming_rfq.originator %>
      <br />
      Forwarder: <%= @incoming_rfq.from %>
    </section>
  </aside>
  <div class="incoming_rfqs">
    <table>
      <thead>
      <td>Part No.</td>
      <td>Description</td>
      <td>Quantity</td>
      <td>Required Delivery</td>
      </thead>
      <%= render @incoming_rfq_items %>
    </table>
  </div>
</div>
<br />
<div align=center><%= link_to "Back to Incoming RFQs", incoming_rfqs_path %></div>