config/routes.rb
Artie::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :customers
  resources :incoming_rfqs
  resources :parts
  resources :drawings

  root to: 'static_pages#home'
  match '/createcustomer',  to: 'customers#new'
  match '/createuser',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/part.rb
# == Schema Information
#
# Table name: parts
#
#  id                           :integer          not null, primary key
#  customer_domain              :string(255)
#  part_number                  :string(255)
#  part_revision                :string(255)
#  part_ecn                     :string(255)
#  drawing_number               :string(255)
#  drawing_revision             :string(255)
#  description                  :string(255)
#  psl                          :string(255)
#  material_temperature         :string(255)
#  material_class               :string(255)
#  material_specification_short :text
#  material_specification_full  :text
#  process_specification_short  :text
#  process_specification_full   :text
#  stamping_specification_full  :text
#  stamping_specification_psl   :boolean
#  stamping_type                :string(255)
#  stamping_information         :text
#  attached_bom_file_name       :string(255)
#  attached_bom_content_type    :string(255)
#  attached_bom_file_size       :integer
#  attached_bom_updated_at      :datetime
#  created_at                   :datetime         not null
#  updated_at                   :datetime         not null
#  approved                     :boolean          default(FALSE)
#  approver_user_id             :integer
#

class Part < ActiveRecord::Base

  attr_accessible :attached_bom, :customer_domain, :description, :drawing_number, :drawing_revision, :material_class, :material_specification_full, :material_specification_short, :material_temperature, :part_ecn, :part_number, :part_revision, :process_specification_full, :process_specification_short, :psl, :stamping_information, :stamping_specification_full, :stamping_specification_psl, :stamping_type
  has_attached_file :attached_bom
  serialize :material_specification_short
  serialize :material_specification_full
  serialize :process_specification_short
  serialize :process_specification_full
  serialize :stamping_specification_full
  serialize :stamping_information

  before_save { |part| part.customer_domain = customer_domain.downcase }

  VALID_DOMAIN_REGEX = /[a-z\d\-.]+\.[a-z]+\z/i
  validates :customer_domain, presence: true, format: { with: VALID_DOMAIN_REGEX }
  validates :part_number, presence: true, length: { maximum: 100 }
  validates_uniqueness_of :part_number, :scope => :part_revision

  default_scope order: 'parts.created_at DESC'

end

app/controllers/parts_controller.rb
class PartsController < ApplicationController

  before_filter :internal_user

  # NOT implemented
  def edit
    @part = Part.find(params[:id])
  end

  def update
    @part = Part.find(params[:id])
    if @part.update_attributes(params[:part])
      flash[:success] = "Part changes saved"
      redirect_to @part
    else
      render 'edit'
    end
  end

  def show
    @part = Part.find(params[:id])
  end

  # NOT implemented
  def new
    @part = Part.new
  end

  def create
    @part = Part.new(params[:part])
    if @part.save
      flash[:success] = "New Part created"
      redirect_to @part
    else
      render 'new'
    end
  end

  def index
    @parts = Part.paginate(page: params[:page])
  end

  def destroy
    Part.find(params[:id]).destroy
    flash[:success] = "Part deleted"
    redirect_to parts_url
  end

end

app/views/parts/_part.html.erb
<% full_part_number = "#{part.part_number} Rev #{part.part_revision}" %>
<li>
  <%= link_to full_part_number, part %>
  | <%= part.description %>
  <% if current_user.admin? %>
      | <%= link_to "delete", part, method: :delete,
                    data: { confirm: "Are you sure you want to delete this?" } %>
  <% end %>
</li>

app/views/parts/index.html.erb
<% provide(:title, 'Parts DB') %>
<h1>Parts DB</h1>

<%= will_paginate %>

<ul class="parts">
  <%= render @parts %>
</ul>

<%= will_paginate %>

app/views/parts/show.html.erb
<% provide(:title, @part.part_number) %>
<% @drawing = Drawing.where(:drawing_number=> @part.drawing_number, :drawing_revision => @part.drawing_revision).find(params[:id]) %>
<%
   flash.now[:error] = ''
   flash.now[:error] << "Part not vetted! " unless @part.approved
   flash.now[:error] << "Drawing not vetted! " unless @drawing.approved
%>
<h1>
  <%= @part.part_number %> Rev <%= @part.part_revision %>
</h1>
<div class="row">
  <aside class="span4">
    <section class="parts">
      <table>
        <tr>
          <td><b>Customer</b></td>
          <td><%= @part.customer_domain %></td>
        </tr>
        <tr>
          <td><b>Description</b></td>
          <td><%= @part.description %></td>
        </tr>
        <tr>
          <td><b>Material</b></td>
          <td><%= @part.material_specification_short.join(", ") %></td>
        </tr>
        <tr>
          <td><b>Stamping</b></td>
          <td><%= @part.stamping_specification_full.join(" ") %></td>
        </tr>
        <tr>
          <td><b>Processes</b></td>
          <td><%= @part.process_specification_short.join(", ") %></td>
        </tr>
        <tr>
          <td><b>Weight</b></td>
          <td><%= @drawing.weight %> <%= @drawing.weight_unit %></td>
        </tr>
        <tr>
          <td><b>Attachments</b></td>
          <td><%= link_to "View BOM", @part.attached_bom.url %><br /><%= link_to "View Drawing", @drawing.attached_drawing.url %></td>
        </tr>
      </table>
    </section>
  </aside>
</div>
<br />
<div align=center><%= link_to "Back to Parts", parts_path %></div>