config/routes.rb
Artie::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :customers
  resources :incoming_rfqs
  resources :parts
  resources :drawings

  root to: 'static_pages#home'
  match '/createcustomer',  to: 'customers#new'
  match '/createuser',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/drawing.rb
# == Schema Information
#
# Table name: drawings
#
#  id                            :integer          not null, primary key
#  customer_domain               :string(255)
#  drawing_number                :string(255)
#  drawing_revision              :string(255)
#  shape                         :string(255)
#  round_outside_diameter        :float
#  round_inside_diameter         :float
#  round_length                  :float
#  flat_length                   :float
#  flat_width                    :float
#  flat_thickness                :float
#  dimension_unit                :string(255)
#  weight                        :float
#  weight_unit                   :string(255)
#  threads                       :text
#  attached_drawing_file_name    :string(255)
#  attached_drawing_content_type :string(255)
#  attached_drawing_file_size    :integer
#  attached_drawing_updated_at   :datetime
#  created_at                    :datetime         not null
#  updated_at                    :datetime         not null
#  approved                      :boolean          default(FALSE)
#  approver_user_id              :integer
#

class Drawing < ActiveRecord::Base

  attr_accessible :attached_drawing, :customer_domain, :dimension_unit, :drawing_number, :drawing_revision, :flat_length, :flat_thickness, :flat_width, :round_inside_diameter, :round_length, :round_outside_diameter, :shape, :threads, :weight, :weight_unit
  has_attached_file :attached_drawing
  serialize :threads

  before_save { |drawing| drawing.customer_domain = customer_domain.downcase }

  VALID_DOMAIN_REGEX = /[a-z\d\-.]+\.[a-z]+\z/i
  validates :customer_domain, presence: true, format: { with: VALID_DOMAIN_REGEX }
  validates :drawing_number, presence: true, length: { maximum: 100 }
  validates_uniqueness_of :drawing_number, :scope => :drawing_revision

end

app/controllers/drawings_controller.rb
class DrawingsController < ApplicationController

  before_filter :internal_user

  # NOT implemented
  def edit
    @drawing = Drawing.find(params[:id])
  end

  def update
    @drawing = Drawing.find(params[:id])
    if @drawing.update_attributes(params[:drawing])
      flash[:success] = "Drawing changes saved"
      redirect_to @drawing
    else
      render 'edit'
    end
  end

  def show
    @drawing = Drawing.find(params[:id])
  end

  # NOT implemented
  def new
    @drawing = Drawing.new
  end

  def create
    @drawing = Drawing.new(params[:drawing])
    if @drawing.save
      flash[:success] = "New Drawing created"
      redirect_to @drawing
    else
      render 'new'
    end
  end

  def index
    @drawings = Drawing.paginate(page: params[:page])
  end

  def destroy
    Drawing.find(params[:id]).destroy
    flash[:success] = "Drawing deleted"
    redirect_to drawings_url
  end

end

app/views/drawings/_drawing.html.erb
<% full_drawing_number = "#{drawing.drawing_number} Rev #{drawing.drawing_revision}" %>
<li>
  <%= link_to full_drawing_number, drawing %>
  <% if current_user.admin? %>
      | <%= link_to "delete", drawing, method: :delete,
                    data: { confirm: "Are you sure you want to delete this?" } %>
  <% end %>
</li>

app/views/drawings/index.html.erb
<% provide(:title, 'Drawings DB') %>
<h1>Drawings DB</h1>

<%= will_paginate %>

<ul class="drawings">
  <%= render @drawings %>
</ul>

<%= will_paginate %>

app/views/drawings/show.html.erb
<% provide(:title, @drawing.drawing_number) %>
<h1>
  <%= @drawing.drawing_number %> Ver <%= @drawing.drawing_revision %>
</h1>
<div class="row">
  <aside class="span4">
    <section class="drawings">
      <table>
        <tr>
          <td><b>Customer</b></td>
          <td><%= @drawing.customer_domain %></td>
        </tr>
        <tr>
          <td><b>Attachment</b></td>
          <td><%= link_to "View Original Drawing", @drawing.attached_drawing.url %></td>
        </tr>
      </table>
    </section>
  </aside>
</div>
<br />
<div align=center><%= link_to "Back to Drawings", drawings_path %></div>