config/routes.rb
Artie::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :customers
  resources :incoming_rfqs
  resources :parts
  resources :drawings

  root to: 'static_pages#home'
  match '/createcustomer',  to: 'customers#new'
  match '/createuser',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Copyright © 2013-2014 Tang Technical Services Pte. Ltd. All rights reserved.
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Tang Technical", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <%= current_user.email %> <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Change Password", edit_user_path(current_user) %></li>
                  <li><%= link_to "Sign Out",        signout_path, method: "delete" %></li>
                </ul>
              </li>
              <% if current_user.admin? %>
                  <li id="fat-menu" class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Site Administration <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "List All Users",  users_path %></li>
                      <li><%= link_to "Add New User", createuser_path %></li>
                      <li class="divider"></li>
                      <li><%= link_to "List All Customers",  customers_path %></li>
                      <li><%= link_to "Add New Customer", createcustomer_path %></li>
                    </ul>
                  </li>
              <% end %>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>